default: &default
  adapter: postgresql
  database: blog
  username: postgres
  password: root
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: utf8

development:
  <<: *default
  database: blog
